#!/bin/bash
SERVICE_LIST="ROLE_MANAGEMENT"
CONFIG_SCRIPT=config.py
TEMP_PATH="template"
TEMP_FILE_NAME="role.temp"
TEMP_ENV_FILE="temp-env.sh"
call_get_config()
{
	cp "$TEMP_PATH/$TEMP_FILE_NAME" TEMP_ENV_FILE
 	vim TEMP_ENV_FILE
 	source TEMP_ENV_FILE

}

 func_role_add()
 {
 	call_get_config
 	python $CONFIG_SCRIPT "role_add"
 	rm TEMP_ENV_FILE

 	#shell api
 	#keystone role-add --name $ROLENAME
 	keystone role-list
}
func_role_delete()
{
	local ROLE_NAME=$3
	if [ $# -le 2 ];then
		echo "You need use this command with an argument of the name of role"
		exit 1
	fi
	#python $CONFIG_SCRIPT "role_delete"  $ROLE_NAME

	#shell api
	keystone role-delete $ROLE_NAME
	keystone role-list
}
func_role_clean()
{
	export CLEAN_CONFRIM
 	if  [ -z $CLEAN_CONFRIM ]; then
		read -p "Do you really want to clean all roles? [Y/n]" CLEAN_CONFRIM
	fi
	if [ 'y' = $CLEAN_CONFRIM -o 'Y' = $CLEAN_CONFRIM ]; then
		python $CONFIG_SCRIPT "role_clean"
	fi
}